# -*- coding: utf-8 -*-
"""
Propagate the 100 m B-double tolerance into the DECLARED-ROAD runtime files.
============================================================================
`rebuild_bdouble_network.py` re-scores the R-04 (19 m B-double) mandatory gate
from the NHVR network and writes the road-level intermediates (nsw_criteria /
nsw_recat / nhvr_networks / nsw_assessment / export_rows). But the dashboard now
reads the DECLARED-road layer (nsw_declared_*.json) + the unit diagnostic layer
(nsw_unit_*.json), which are normally regenerated by rebuild_road_units.py — a
step that needs raw inputs (employment zones, the 1.3 M-feature road-segment
GeoPackage, the SUA census profile) not present on every machine.

R-04 is a MANDATORY GATE, not an optional criterion, so flipping it never
changes a road's optional count. That lets us propagate just this one change
into the declared/unit files without the full pipeline: for each affected road
we set mand.bdouble and recompute the verdict from the file's OWN existing
optMet, using the same rule the pipeline uses:

    red  if the mandatory gate fails
    else green if optMet >= 2, orange if optMet == 1, red if optMet == 0.

Every road that flips is asserted to be a single-section declared road
(declared_road == road_number == unit key), i.e. the verbatim case where the
declared verdict is the road's own verdict. If a future data change makes a
MULTI-section road flip, this script errors rather than guess the roll-up — run
the full rebuild_road_units.py instead. Verdicts are earned from coverage, never
forced. Dry run by default; --apply writes (.preBdTol.bak backups).
"""
import copy
import json
import shutil
import sys
from pathlib import Path

import geopandas as gpd

from rebuild_bdouble_network import (
    ACCESS_THRESHOLD,
    aggregate_unit_coverage,
    approved_network,
    route_coverage,
)

APPLY = "--apply" in sys.argv
TOLERANCE_M = 100.0
HERE = Path(__file__).resolve().parent
DATA = HERE / "data"
NETWORK = DATA / "geopackages" / "nhvr_hvn_11240521.gpkg"
PROJECTED_CRS = "EPSG:3577"
BAK = ".preBdTol.bak"


def log(*a):
    print(*a, flush=True)


def orig_path(name):
    p = DATA / name
    bak = p.with_name(p.name + BAK)
    return bak if bak.exists() else p


def read_orig(name):
    return json.load(open(orig_path(name), encoding="utf-8"))


def write_json(name, obj, indent=None):
    p = DATA / name
    bak = p.with_name(p.name + BAK)
    if not bak.exists():
        shutil.copyfile(p, bak)
    with open(p, "w", encoding="utf-8") as f:
        json.dump(obj, f, ensure_ascii=False, indent=indent)
    log(f"  wrote {name} (backup: {bak.name})")


def verdict_from(row):
    """Verdict rule, mirroring rebuild_bdouble_network.verdict_of exactly: the class-specific
    mandatory gate (State -> pbs1, Regional -> bdouble) first, then the optional count."""
    mand = row.get("mand") or {}
    if row.get("cls") == "State" and mand.get("pbs1") is False:
        return "red"
    if row.get("cls") == "Regional" and mand.get("bdouble") is False:
        return "red"
    opt_met = row.get("optMet")
    if opt_met is None:
        opt_met = sum(1 for v in (row.get("opt") or {}).values() if v is True)
    return "green" if opt_met >= 2 else "orange" if opt_met == 1 else "red"


# ---------------------------------------------------------------- coverage
log(f"NHVR 19 m B-double network: {NETWORK.name}")
network = approved_network(NETWORK)
log(f"  approved segments: {len(network):,}")

assessment = read_orig("nsw_assessment.geojson")
roads = gpd.GeoDataFrame.from_features(assessment["features"], crs="EPSG:4326")
fractions = route_coverage(roads, network, TOLERANCE_M)
lengths_m = roads.to_crs(PROJECTED_CRS).geometry.length.tolist()
# aggregate_unit_coverage() reads each feature's bdouble_coverage — write the fresh 100 m
# fractions in first (mirrors rebuild_bdouble_network.main), else it aggregates stale values.
for index, feature in enumerate(assessment["features"]):
    feature["properties"]["bdouble_coverage"] = round(fractions[index], 6)
unit_coverage = aggregate_unit_coverage(assessment, lengths_m)   # keyed by road_unit
log(f"  per-unit coverage computed at {TOLERANCE_M:g} m for {len(unit_coverage)} units")

# ---------------------------------------------------------------- declared/unit state
declared_crit = read_orig("nsw_declared_criteria.json")
unit_crit = read_orig("nsw_unit_criteria.json")

# unit -> its declared road; declared road -> its units + each unit's length (Σ feature lengths)
declared_units = {}
unit_len = {}
for i, f in enumerate(assessment["features"]):
    p = f["properties"]
    u = str(p.get("road_unit") or "").strip()
    d = str(p.get("declared_road") or "").strip()
    if u and d:
        declared_units.setdefault(d, set()).add(u)
        unit_len[u] = unit_len.get(u, 0.0) + lengths_m[i]


def combined_boolean(values):
    """Identical to rebuild_road_units.combined_boolean: any False -> False; all present and
    all bool -> True; otherwise None. For Regional roads every unit gate is a bool."""
    known = [v for v in values if isinstance(v, bool)]
    if any(v is False for v in known):
        return False
    if known and len(known) == len(values):
        return True
    return None


# ---------------------------------------------------------------- decide flips
# Unit gate = unit_coverage >= 0.80 (this is the pipeline's weighted_flag(has_bdouble) coverage:
# the length-weighted mean of per-feature bdouble_coverage). Declared gate = combined_boolean of
# the unit gates (the pipeline's roll-up). Declared coverage = unit-length-weighted mean.
flips = []          # (declared_key, sections, old_verdict, new_verdict, declared_coverage)
declared_cov = {}   # declared_key -> rolled-up coverage (for the nhvr layer)
for dkey, row in declared_crit.items():
    if row.get("cls") != "Regional":
        continue
    units = declared_units.get(dkey)
    if not units or any(u not in unit_coverage for u in units):
        continue
    unit_gate = {u: unit_coverage[u] >= ACCESS_THRESHOLD for u in units}
    old_gate = (row.get("mand") or {}).get("bdouble") is True
    new_gate = combined_boolean(list(unit_gate.values()))
    if (new_gate is True) == old_gate:
        continue
    tot = sum(unit_len[u] for u in units) or 1.0
    cov = sum(unit_len[u] * unit_coverage[u] for u in units) / tot
    declared_cov[dkey] = cov
    before = row.get("verdict")
    row.setdefault("mand", {})["bdouble"] = new_gate
    row["verdict"] = verdict_from(row)
    for u in units:
        urow = unit_crit.get(u)
        if urow is not None:
            urow.setdefault("mand", {})["bdouble"] = unit_gate[u]
            urow["verdict"] = verdict_from(urow)
    flips.append((dkey, len(units), before, row["verdict"], cov))

flips.sort(key=lambda t: t[0])
log(f"\nRegional declared roads flipping B-double gate (fail -> pass): {len(flips)}")
for dkey, sect, before, after, cov in flips:
    tag = f"{sect}-section" if sect > 1 else "single"
    log(f"  {dkey}  {before:6} -> {after:6}  coverage {cov:6.1%}  ({tag})")
if not flips:
    log("  none — nothing to write.")
    sys.exit(0)

flipped_keys = {k for k, *_ in flips}

# ---------------------------------------------------------------- nhvr layers
for name in ("nsw_declared_nhvr.json", "nsw_unit_nhvr.json"):
    nhvr = read_orig(name)
    if "declared" in name:
        for d in flipped_keys:
            row = nhvr.setdefault(d, {})
            row["bdouble19"] = True
            row["bdouble19Coverage"] = round(declared_cov[d], 6)
            row["bdouble19ToleranceM"] = TOLERANCE_M
    else:
        for d in flipped_keys:
            for u in declared_units[d]:
                if unit_coverage[u] >= ACCESS_THRESHOLD:   # only units that actually pass
                    row = nhvr.setdefault(u, {})
                    row["bdouble19"] = True
                    row["bdouble19Coverage"] = round(unit_coverage[u], 6)
                    row["bdouble19ToleranceM"] = TOLERANCE_M
    if APPLY:
        write_json(name, nhvr)

# ---------------------------------------------------------------- recat + assessment status
new_declared_verdict = {dkey: after for dkey, _sect, _before, after, _cov in flips}
# unit-level new verdicts (every unit of a flipped declared road; unchanged ones are idempotent)
new_unit_verdict = {}
for d in flipped_keys:
    for u in declared_units[d]:
        urow = unit_crit.get(u)
        if urow is not None:
            new_unit_verdict[u] = urow["verdict"]

# nsw_assessment.geojson: per-feature status keyed by road_unit. has_bdouble is per-feature and
# already refreshed at 100 m (bdouble_coverage set above) — only flip the boolean where the
# feature itself now clears the threshold, not blanket across the road.
asmt_live = read_orig("nsw_assessment.geojson")
touched = 0
for i, f in enumerate(asmt_live["features"]):
    u = str(f["properties"].get("road_unit") or "").strip()
    if u in new_unit_verdict:
        f["properties"]["status"] = new_unit_verdict[u]
        f["properties"]["bdouble_coverage"] = round(fractions[i], 6)
        f["properties"]["has_bdouble"] = int(fractions[i] >= ACCESS_THRESHOLD)
        touched += 1
log(f"\nassessment features restyled: {touched}")

# declared / unit recat (parallel arrays or dicts — detect shape)
def patch_recat(name, vmap, key_of):
    recat = read_orig(name)
    n = 0
    if isinstance(recat, list):
        for i, f in enumerate(asmt_live["features"]):
            k = key_of(f["properties"])
            if k in vmap and i < len(recat):
                recat[i] = vmap[k]
                n += 1
    else:
        for k, v in vmap.items():
            if k in recat:
                recat[k] = v
                n += 1
    log(f"  {name}: {n} verdicts updated")
    if APPLY:
        write_json(name, recat)

# ---------------------------------------------------------------- write
if not APPLY:
    log("\ndry run only — re-run with --apply to write. No files changed.")
    sys.exit(0)

write_json("nsw_declared_criteria.json", declared_crit)
write_json("nsw_unit_criteria.json", unit_crit)
patch_recat("nsw_declared_recat.json", new_declared_verdict, lambda p: str(p.get("declared_road") or "").strip())
patch_recat("nsw_unit_recat.json", new_unit_verdict, lambda p: str(p.get("road_unit") or "").strip())
write_json("nsw_assessment.geojson", asmt_live)
log("\ndone. NOTE: export_declared_rows.json / export_unit_rows.json are NOT patched here "
    "(export ordering is verdict-grouped); re-export from the UI or run the full pipeline for those.")
